// <auto-generated />
using System;
using HardTrain.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HardTrain.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230202101230_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HardTrain.DAL.Entities.TrainingScope.Exersice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("DefaultReps")
                        .HasColumnType("int");

                    b.Property<int>("DefaultTime")
                        .HasColumnType("int");

                    b.Property<int>("DefaultWeight")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exersices");
                });

            modelBuilder.Entity("HardTrain.DAL.Entities.TrainingScope.Training", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("HardTrain.DAL.Entities.TrainingScope.TrainingExersice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExersiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrainingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExersiceId");

                    b.HasIndex("TrainingId");

                    b.ToTable("TrainingExersices");
                });

            modelBuilder.Entity("HardTrain.DAL.Entities.UserResultScope.ExersiceResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExersiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<Guid>("TrainingResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExersiceId");

                    b.HasIndex("TrainingResultId");

                    b.ToTable("ExersiceResults");
                });

            modelBuilder.Entity("HardTrain.DAL.Entities.UserResultScope.TrainingResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TrainingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId");

                    b.HasIndex("UserId");

                    b.ToTable("TrainingResults");
                });

            modelBuilder.Entity("HardTrain.DAL.Entities.UserResultScope.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HardTrain.DAL.Entities.TrainingScope.TrainingExersice", b =>
                {
                    b.HasOne("HardTrain.DAL.Entities.TrainingScope.Exersice", "Exersice")
                        .WithMany()
                        .HasForeignKey("ExersiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HardTrain.DAL.Entities.TrainingScope.Training", "Training")
                        .WithMany("TrainingExersices")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exersice");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("HardTrain.DAL.Entities.UserResultScope.ExersiceResult", b =>
                {
                    b.HasOne("HardTrain.DAL.Entities.TrainingScope.Exersice", "Exersice")
                        .WithMany()
                        .HasForeignKey("ExersiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HardTrain.DAL.Entities.UserResultScope.TrainingResult", "TrainingResult")
                        .WithMany("ExersiceResults")
                        .HasForeignKey("TrainingResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exersice");

                    b.Navigation("TrainingResult");
                });

            modelBuilder.Entity("HardTrain.DAL.Entities.UserResultScope.TrainingResult", b =>
                {
                    b.HasOne("HardTrain.DAL.Entities.TrainingScope.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HardTrain.DAL.Entities.UserResultScope.User", "User")
                        .WithMany("TrainingResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Training");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HardTrain.DAL.Entities.TrainingScope.Training", b =>
                {
                    b.Navigation("TrainingExersices");
                });

            modelBuilder.Entity("HardTrain.DAL.Entities.UserResultScope.TrainingResult", b =>
                {
                    b.Navigation("ExersiceResults");
                });

            modelBuilder.Entity("HardTrain.DAL.Entities.UserResultScope.User", b =>
                {
                    b.Navigation("TrainingResults");
                });
#pragma warning restore 612, 618
        }
    }
}
