// <auto-generated />
using System;
using HardTrain.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HardTrain.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230124210649_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HardTrain.DAL.Entities.ExersiceEntities.Exersice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exersices");
                });

            modelBuilder.Entity("HardTrain.DAL.Entities.ExersiceEntities.Training", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TrainingTemplates");
                });

            modelBuilder.Entity("HardTrain.DAL.Entities.ExersiceEntities.TrainingExersice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExersiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExersiceKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<Guid>("TrainingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrainingKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExersiceKey");

                    b.HasIndex("TrainingKey");

                    b.ToTable("ExersiceTemplates");
                });

            modelBuilder.Entity("HardTrain.DAL.Entities.ExersiceEntities.TrainingExersice", b =>
                {
                    b.HasOne("HardTrain.DAL.Entities.ExersiceEntities.Exersice", "Exersice")
                        .WithMany()
                        .HasForeignKey("ExersiceKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HardTrain.DAL.Entities.ExersiceEntities.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exersice");

                    b.Navigation("Training");
                });
#pragma warning restore 612, 618
        }
    }
}
